# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://okbecause.github.io
title: Because LLC
email: billyc@okbecause.com
author: Billy Charlton
description: Technology, Data, and Transportation Consulting
copyright: 'Copyright &copy; 2016 Because LLC. All Rights Reserved.'
credits: 'Credits: Landing Page theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/okbecause
  - title: twitter
    url: https://twitter.com/billyinseattle
